model_type: yolov8n.pt
pretrained: False
seed: 0
imgsz: 640
batch: 8
epochs: 6
optimizer: Adam # other choices=['SGD', 'Adam', 'AdamW', 'RMSProp']
lr0: 0.001  # learning rate
name: 'yolov8n_exp_v0277' # experiment name
train_mode : 'Train'

